kind: pipeline
name: chatroom_drone

steps:
- name: stage
  image: alpine:3.7
  commands:
  - echo "stage"
  when:
    event: [ promote ]
    target: [ staging ]

- name: production
  image: alpine:3.7
  commands:
  - echo "production"
  when:
    event: [ promote ]
    target: [ production ]

- name: testing
  image: alpine:3.7
  commands:
  - echo "testing"
  when:
    event: [ promote ]
    target: [ production ]